/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
    }
    interface MyEvents {
    }
    interface MyFunctionComponent {
    }
    interface MyLifecycle {
    }
}
export interface MyEventsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyEventsElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyEventsElement extends Components.MyEvents, HTMLStencilElement {
    }
    var HTMLMyEventsElement: {
        prototype: HTMLMyEventsElement;
        new (): HTMLMyEventsElement;
    };
    interface HTMLMyFunctionComponentElement extends Components.MyFunctionComponent, HTMLStencilElement {
    }
    var HTMLMyFunctionComponentElement: {
        prototype: HTMLMyFunctionComponentElement;
        new (): HTMLMyFunctionComponentElement;
    };
    interface HTMLMyLifecycleElement extends Components.MyLifecycle, HTMLStencilElement {
    }
    var HTMLMyLifecycleElement: {
        prototype: HTMLMyLifecycleElement;
        new (): HTMLMyLifecycleElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-events": HTMLMyEventsElement;
        "my-function-component": HTMLMyFunctionComponentElement;
        "my-lifecycle": HTMLMyLifecycleElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
    }
    interface MyEvents {
        "onChangeCompleted"?: (event: MyEventsCustomEvent<boolean>) => void;
    }
    interface MyFunctionComponent {
    }
    interface MyLifecycle {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-events": MyEvents;
        "my-function-component": MyFunctionComponent;
        "my-lifecycle": MyLifecycle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-events": LocalJSX.MyEvents & JSXBase.HTMLAttributes<HTMLMyEventsElement>;
            "my-function-component": LocalJSX.MyFunctionComponent & JSXBase.HTMLAttributes<HTMLMyFunctionComponentElement>;
            "my-lifecycle": LocalJSX.MyLifecycle & JSXBase.HTMLAttributes<HTMLMyLifecycleElement>;
        }
    }
}
