/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
    }
    interface MyLifecycle {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyLifecycleElement extends Components.MyLifecycle, HTMLStencilElement {
    }
    var HTMLMyLifecycleElement: {
        prototype: HTMLMyLifecycleElement;
        new (): HTMLMyLifecycleElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-lifecycle": HTMLMyLifecycleElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
    }
    interface MyLifecycle {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-lifecycle": MyLifecycle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-lifecycle": LocalJSX.MyLifecycle & JSXBase.HTMLAttributes<HTMLMyLifecycleElement>;
        }
    }
}
